Stage.scaleMode = "noScale";
menu_cm = new ContextMenu();
menu_cm.builtInItems.forward_back = false;
menu_cm.builtInItems.loop = false;
menu_cm.builtInItems.play = false;
menu_cm.builtInItems.print = false;
menu_cm.builtInItems.quality = true;
menu_cm.builtInItems.rewind = false;
menu_cm.builtInItems.save = false;
menu_cm.builtInItems.zoom = true;
_root.menu = menu_cm;
_global.baseUrl = "https://andy-sudo-lab.github.io/v_15/";
loadMovie(_global.baseUrl + "data0.swf",_root.checkMC.m1);
loadMovie(_global.baseUrl + "dataZ.swf",_root.checkMC.m2);
