this.stop();
menu_cm = new ContextMenu();
menu_cm.builtInItems.forward_back = false;
menu_cm.builtInItems.loop = false;
menu_cm.builtInItems.play = false;
menu_cm.builtInItems.print = false;
menu_cm.builtInItems.quality = false;
menu_cm.builtInItems.rewind = false;
menu_cm.builtInItems.save = false;
menu_cm.builtInItems.zoom = false;
_root.menu = menu_cm;
